# Generated by Django 4.2.5 on 2023-09-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_request_status', models.CharField(max_length=10)),
                ('from_friend_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_profile', to='authentication_app.profile')),
                ('to_friend_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_profile', to='authentication_app.profile')),
            ],
        ),
    ]
