# Generated by Django 4.2.5 on 2023-09-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0003_friendshipmodels'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendshipmodels',
            unique_together={('from_friend_request', 'to_friend_request')},
        ),
    ]
