# Generated by Django 4.2.5 on 2023-09-09 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0003_postcomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSharings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_share', to='blog_app.posts')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_share_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('shared_by', 'blog_post')},
            },
        ),
    ]
